name: Compile LaTeX

on:
  push:
    branches: [ main ]
    paths:
      - '**.tex'
      - '.github/workflows/compile-latex.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install TeX Live
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y -qq texlive-latex-base texlive-latex-recommended \
          texlive-latex-extra texlive-xetex texlive-fonts-recommended \
          texlive-fonts-extra texlive-lang-chinese latexmk xz-utils
    - name: Compile main.pdf
      run: |
        cd $GITHUB_WORKSPACE
        latexmk -xelatex -interaction=nonstopmode main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-PDFs
        path: "*.pdf"
        if-no-files-found: error
